### PR TITLE
HTML Gen and Cells Cleanup

### PR DESCRIPTION
**Pull request by darth-cheney**
This PR removes all HTMLElement generation from Cells (along with the HTML modules and tests) and cleans up related code.

## Motivation and Context

Because we no longer use any HTML generated from the Python side, the time has come to remove all the extra HTMLElement generation code from cells. This will help reduce the amount of code while also providing some additional advantages.

  
Note that this will also better prepare us for removing the use of replacement strings entirely, as well as refactoring specific WS messages and Cell lifecycle events.
  
Overall, this means *we no longer have to worry about `contents` of the Cell*

## Approach

For the most part, this process simply involved removing HTMLElement generation and the setting of `self.contents` on Cell classes.
  
Note that I also did the following, which is important to know:
* Removed a warning about "replacements not all being used up" that would crash the UI. Because replacements are generated on the front-end for the moment, we no longer need this check.
* Removed `multiReplace` and anything that uses it. It was no longer needed.
* Removed `contents` etc from being sent over the socket (in `updateMessageFor`). This should help reduce the amount of data going over the wire in outbound socket messages. It was no longer needed.
* Removed all HTMLElement modules and tests
* Removed Cells tests that checked for HTML validity. These are no longer needed
* Minor updates / refactorings to Cell/Component combinations as needed during the process, especially `Button` and `Clickable`

## How Has This Been Tested?

I have refactored the Cells tests (all passing) and tested changes incrementally in the demo web frontend as I went.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
  
## Closes ##
#134 
#135

### CODE REVIEW

**Comment by braxtonmckee** [comment]
This looks great, but I tried squashing it, rebasing it and rebuilding it and the playground looks messed up (cards in the wrong spot etc.). I pushed it up as `eric-remove-html-gen-rebased` for you to check out.

**Comment by darth-cheney** [comment]
@braxtonmckee I'm not sure we are seeing the same thing. I have just made a fresh install of your rebased branch and the playground looks pretty much as it has for the past week or two. Can you post a screenshot showing what you're seeing that's wrong?

**Comment by braxtonmckee** [comment]
Weird - this looks like it works now. I noticed that the Modal dialogs are not working, but I think that happened before this change. If you rebase this, squash, and rebuild, I think it's good to go. I'll file a ticket for the dialogs.

**Comment by darth-cheney** [comment]
@braxtonmckee Ok I've squashed and rebased. CI is failing but it doesn't appear to be one of the cells tests -- some socket related thing

**Pull request merged**
